version: '3.3'
services:
  ndjs-dz4-app:
    build:
      context: ./books
      dockerfile: Dockerfile
    container_name: ndjs-4-books
    entrypoint: ['yarn', 'watch']
    env_file:
      - .env
    ports:
      - 80:${PORT:-3000}
    volumes:
      - "./books:/var/www"
    links:
      - ndjs-dz4-counter
      - ndjs-dz4-mongo
    depends_on:
      - ndjs-dz4-mongo
  ndjs-dz4-mongo:
    image: mongo:5.0.3
    container_name: ndjs-4-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_CONNECT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_CONNECT_PASSWORD:-password}
    volumes:
      - 'mongo_new_data:/data/db'
  ndjs-dz4-counter:
    build:
      context: ./counter
      dockerfile: Dockerfile
    entrypoint: ['yarn', 'watch']
    env_file:
      - .env
    volumes:
      - "./counter/src:/var/www/src"
    ports:
      - 5000:${PORT:-5000}
    links:
      - ndjs-dz4-redis

  ndjs-dz4-redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
volumes:
  redis_data:
  mongo_new_data:
