
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndjs-counter
  namespace: default
spec:
  selector:
    matchLabels:
      app: ndjs-counter
  template:
    metadata:
      labels:
        app: ndjs-counter
    spec:
      containers:
        - name: ndjs-counter
          image: "ndjs-4-counter"
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ndjs-counter-ingress
  namespace: kube-system
spec:
  ingressClassName: nginx
  rules:
    - host: ndjs-dz4-counter.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ndjs-counter
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ndjs-counter
  namespace: kube-system
spec:
  type: ExternalName
  externalName: ndjs-counter.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: ndjs-counter
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app: ndjs-counter