"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.container = void 0;
require("reflect-metadata");
const inversify_1 = require("inversify");
const book_repository_1 = require("./repository/book.repository");
const book_service_1 = require("./service/book.service");
const container = new inversify_1.Container();
exports.container = container;
container.bind(book_repository_1.BookRepository).toSelf();
container.bind(book_service_1.BookService).toSelf();
