
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndjs-books
  namespace: default
spec:
  selector:
    matchLabels:
      app: ndjs-books
  template:
    metadata:
      labels:
        app: ndjs-books
    spec:
      containers:
        - name: ndjs-books
          image: "ndjs-4-books"
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: DEMO_GREETING
              value: "Hello from the environment"
            - name: DEMO_FAREWELL
              value: "Such a sweet sorrow"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ndjs-books-ingress
  namespace: kube-system
spec:
  ingressClassName: nginx
  rules:
    - host: ndjs-dz4-counter.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ndjs-books
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ndjs-books
  namespace: kube-system
spec:
  type: ExternalName
  externalName: ndjs-books.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: ndjs-books
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app: ndjs-books